/**
 * @file      lorawan_commissioning.h
 *
 * @brief     End device commissioning parameters
 *
 * The Clear BSD License
 * Copyright Semtech Corporation 2024. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted (subject to the limitations in the disclaimer
 * below) provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the Semtech corporation nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY
 * THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
 * CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
 * NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL SEMTECH CORPORATION BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef LORAWAN_COMMISSIONING_H
#define LORAWAN_COMMISSIONING_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * -----------------------------------------------------------------------------
 * --- DEPENDENCIES ------------------------------------------------------------
 */

/*
 * -----------------------------------------------------------------------------
 * --- PUBLIC MACROS -----------------------------------------------------------
 */

/*
 * -----------------------------------------------------------------------------
 * --- PUBLIC CONSTANTS --------------------------------------------------------
 */

/**
 * @brief Use internal credential
 * @remark By setting true the credentials defined in this document will not be used
 */
#define USE_LR11XX_CREDENTIALS false

/**
 * @brief IEEE Organizationally Unique Identifier ( OUI ) (big endian)
 * @remark This is unique to a company or organization
 */
#define IEEE_OUI 0x00, 0x00, 0x00

/**
 * @brief Device IEEE EUI (big endian)
 *
 * @remark In this application the value is automatically generated by calling
 *         lr1110_modem_get_dev_eui function
 */
#define LORAWAN_DEVICE_EUI                     \
    {                                          \
        0x48, 0xE6, 0x63, 0xFF, 0xFE, 0x30, 0x00, 0x35 \
    }
#define LORAWAN_DEVICE_EUI_LEN 8

/**
 * @brief App/Join server IEEE EUI (big endian)
 */
#define LORAWAN_JOIN_EUI                               \
    {                                                  \
        0x48, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x35 \
    }
#define LORAWAN_JOIN_EUI_LEN 8

/**
 * @brief loRaWAN Network Key (big endian)
 */
#define LORAWAN_NWK_KEY                                                                                \
    {                                                                                                  \
        0x04, 0xDF, 0xC3, 0x23, 0x47, 0x12, 0xE8, 0x63, 0x3C, 0x30, 0x6E, 0xB8, 0x02, 0x7E, 0xDD, 0xAC \
    }
#define LORAWAN_NWK_KEY_LEN 16

/**
 * @brief loRaWAN Application Key (big endian)
 */
#define LORAWAN_APP_KEY                                                                                \
    {                                                                                                  \
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x78 \
    }
#define LORAWAN_APP_KEY_LEN 16

/*
 * -----------------------------------------------------------------------------
 * --- PUBLIC TYPES ------------------------------------------------------------
 */

/*
 * -----------------------------------------------------------------------------
 * --- PUBLIC FUNCTIONS PROTOTYPES ---------------------------------------------
 */

#ifdef __cplusplus
}
#endif

#endif  // LORAWAN_COMMISSIONING_H

/* --- EOF ------------------------------------------------------------------ */
